WORDS = [
    "AMOR", "CASA", "FELIZ", "JOGO", "LIVRO", "MUNDO", "TEMPO", "VIDA",
    "SOL", "LUZ", "MAR", "RIO", "FLOR", "ÁRVORE", "PRAIA", "CAMPO",
    "FUTURO", "PASSADO", "PRESENTE", "FAMÍLIA", "AMIGO", "ESCOLA", "TRABALHO"
]